/** @type {import('tailwindcss').Config} */
export default {
	content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
	darkMode: "class",
	theme: {
		extend: {
			"colors": {
				"surface-container-low": "#f3f3f3",
				"on-error-container": "#93000a",
				"surface-bright": "#f9f9f9",
				"tertiary-fixed": "#e5e2dd",
				"on-secondary-fixed": "#1d1b17",
				"inverse-on-surface": "#f1f1f1",
				"secondary": "#615e58",
				"on-primary-container": "#858383",
				"primary-fixed-dim": "#c8c6c5",
				"primary-container": "#1c1b1b",
				"on-secondary-container": "#65625c",
				"on-surface": "#1b1b1b",
				"surface": "#f9f9f9",
				"outline": "#747878",
				"surface-variant": "#e2e2e2",
				"primary-fixed": "#e5e2e1",
				"on-tertiary-fixed": "#1c1c19",
				"on-primary": "#ffffff",
				"on-tertiary-fixed-variant": "#474743",
				"surface-dim": "#dadada",
				"on-error": "#ffffff",
				"surface-container-lowest": "#ffffff",
				"on-primary-fixed": "#1c1b1b",
				"surface-container-highest": "#e2e2e2",
				"outline-variant": "#c4c7c7",
				"on-tertiary-container": "#858480",
				"inverse-surface": "#303030",
				"secondary-fixed-dim": "#cbc6be",
				"on-primary-fixed-variant": "#474746",
				"tertiary": "#000000",
				"secondary-fixed": "#e7e2da",
				"secondary-container": "#e4dfd7",
				"error-container": "#ffdad6",
				"on-surface-variant": "#444748",
				"primary": "#000000",
				"surface-container-high": "#e8e8e8",
				"surface-container": "#eeeeee",
				"inverse-primary": "#c8c6c5",
				"tertiary-fixed-dim": "#c9c6c2",
				"tertiary-container": "#1c1c19",
				"on-secondary": "#ffffff",
				"on-background": "#1b1b1b",
				"on-tertiary": "#ffffff",
				"on-secondary-fixed-variant": "#494741",
				"background": "#f9f9f9",
				"surface-tint": "#5f5e5e",
				"error": "#ba1a1a"
			},
			"borderRadius": {
				"DEFAULT": "0.125rem",
				"lg": "0.25rem",
				"xl": "0.5rem",
				"full": "0.75rem"
			},
			"spacing": {
				"unit": "8px",
				"gutter": "24px",
				"margin-desktop": "64px",
				"container-max": "1280px",
				"margin-mobile": "20px",
				"section-gap": "120px"
			},
			"fontFamily": {
				"body-md": ["Inter"],
				"label-sm": ["Inter"],
				"headline-md": ["\"Source Serif 4\""],
				"body-lg": ["Inter"],
				"display-lg": ["\"Source Serif 4\""],
				"label-lg": ["Inter"],
				"display-lg-mobile": ["\"Source Serif 4\""],
				"headline-lg": ["\"Source Serif 4\""],
				"logo": ["\"Space Grotesk\"", "sans-serif"]
			},
			"fontSize": {
				"body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
				"label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
				"headline-md": ["32px", { "lineHeight": "40px", "fontWeight": "400" }],
				"body-lg": ["20px", { "lineHeight": "32px", "fontWeight": "400" }],
				"display-lg": ["72px", { "lineHeight": "80px", "letterSpacing": "-0.02em", "fontWeight": "400" }],
				"label-lg": ["14px", { "lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "500" }],
				"display-lg-mobile": ["40px", { "lineHeight": "44px", "letterSpacing": "-0.01em", "fontWeight": "400" }],
				"headline-lg": ["48px", { "lineHeight": "56px", "fontWeight": "400" }]
			}
		},
	},
}
